---
apiVersion: v1
kind: Secret
metadata:
  name: freenas-nfs
  namespace: kube-system
type: Opaque
data:
  # all values should be base64 encoded (ie: echo -n 'https' | base64)
  #
  # note that all values are relative to where the provisioner is running
  # ie: if running the provisioner directly on the FreeNAS server 'localhost'
  # would be a valid 'host' value

  # http|https
  # default: http
  #protocol: aHR0cHM= 

  # default: localhost (for running the provisioner out of cluster directly on FreeNAS node)
  host: "*******"

  # default: 80
  #port: NDQz

  # default: root (api is only available for root currently)
  #username: 
  #password: MS1OdmRUN29XWTFkUVBoMHhMR2dpWndXRHFqUWpHZEJGS3RLa2tmOTFacTlOdTF2RlU5blFLR2FrcUtvQ0JHOFRi
  password: "*******"

  # allow for self-signed/untrusted certs if using https
  # true|false
  # default: false
  allowInsecure: "*******"
  