apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: plex.anasjabri.com
  namespace: plex
spec:
  secretName: plex.anasjabri.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: plex.anasjabri.com
  dnsNames:
  - plex.anasjabri.com