apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: sabnzbd.anasjabri.com
  namespace: sabnzbd
spec:
  secretName: sabnzbd.anasjabri.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: sabnzbd.anasjabri.com
  dnsNames:
  - sabnzbd.anasjabri.com