apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  finalizers:
  - kubernetes.io/pvc-protection
  name: sabnzbd-config
  namespace: sabnzbd
spec:
  storageClassName: freenas-iscsi-csi
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
