- name: add kubernetes to yum repos
  become: yes
  yum_repository:
    name: kubernetes
    description: Kubernetes
    baseurl: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/
    enabled: yes
    gpgcheck: yes
    gpgkey: https://pkgs.k8s.io/core:/stable:/v1.29/rpm/repodata/repomd.xml.key
    exclude:
      - kubelet
      - kubeadm
      - kubectl
      - cri-tools
      - kubernetes-cni
