apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: test.anasjabri.com
  namespace: default
spec:
  secretName: test.anasjabri.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: test.anasjabri.com
  dnsNames:
  - test.anasjabri.com