apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: radarr.anasjabri.com
  namespace: radarr
spec:
  secretName: radarr.anasjabri.com-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  commonName: radarr.anasjabri.com
  dnsNames:
  - radarr.anasjabri.com