apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: nfs-vol
provisioner: nfs.csi.k8s.io
parameters:
  server: 10.0.50.229
  share: /mnt/ssd/k8/nfs
reclaimPolicy: Retain
volumeBindingMode: Immediate
mountOptions:
  - nfsvers=4.1

