---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-claim-iscsi1
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
  storageClassName: iscsi-vol
  selector:
    matchExpressions:
      - key: name
        operator: In
        values: ["data-iscsi-pv"]