# test-claim-nfs.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: test-claim-nfs123
  annotations:
    volume.beta.kubernetes.io/storage-class: "nfs-vol"
spec:
  storageClassName: nfs-vol
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Mi
